import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
  IonContent,
  IonAlert,
  IonCol,
  IonCard,
  IonRow,
  IonCardHeader,
  IonCardTitle,
  IonCardSubtitle,
  IonButton,
  IonFooter,
  IonIcon,
  IonProgressBar,
  IonNote,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonButtons,
  IonSearchbar,
  IonItem,
  IonInput,
  IonCardContent,
  IonLabel,
  IonToggle,
  IonText
} from '@ionic/angular/standalone';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    IonAlert,
    IonContent,
    IonCol,
    IonCard,
    IonRow,
    IonCardHeader,
    IonCardTitle,
    IonCardSubtitle,
    IonButton,
    IonFooter,
    IonIcon,
    IonProgressBar,
    IonNote,
    IonHeader,
    IonToolbar,
    IonTitle,
    IonButtons,
    IonItem,
    IonInput,
    IonCardContent,
    IonSearchbar,
    IonLabel,
    IonToggle,
    IonText
  ],
  exports: [
    CommonModule,
    IonAlert,
    IonContent,
    IonCol,
    IonCard,
    IonRow,
    IonFooter,
    IonCardHeader,
    IonCardTitle,
    IonCardSubtitle,
    IonButton,
    IonIcon,
    IonSearchbar,
    IonProgressBar,
    IonNote,
    IonHeader,
    IonToolbar,
    IonTitle,
    IonButtons,
    IonItem,
    IonInput,
    IonCardContent,
    IonLabel,
    IonToggle,
    IonText
  ]
})
export class IonicBundle {}
